import express from "express";
import signUp from './controllers/signUp';
import login from './controllers/login';
import logout from './controllers/logout';
import getCurrentUser from './controllers/getCurrentUser';
import getAgents from "./controllers/getAgents";
import getAgentByName from './controllers/getAgentByName';
import getAgentByType from './controllers/getAgentByType';
import addAgent from './controllers/addAgent';
import getAvailableAgents from './controllers/getAvailableAgents';
import getAvailableAgentByType from './controllers/getAvailableAgentByType';
import getThread from "./controllers/getThread";
import addThread from './controllers/addThread';
import addPublicThread from './controllers/addPublicThread';
import deleteThread from './controllers/deleteThread';
import addQuery from './controllers/addQuery';
import deleteQuery from './controllers/deleteQuery';
import updateRequestBody from './controllers/updateRequestBody';
import updateResponseBody from './controllers/updateResponseBody';
import createThreadTitle from "./controllers/createThreadTitle";
import updateThreadTitle from './controllers/updateThreadTitle';
import removeThreadTitle from './controllers/removeThreadTitle';
import updateThreadIsBookmarked from './controllers/updateThreadIsBookmarked';
import createResponse from "./controllers/createResponse";
import inferAgentType from './controllers/inferAgentType';
import getThreadUpdatedAt from './controllers/getThreadUpdatedAt';
import getAgentsUpdatedAt from './controllers/getAgentsUpdatedAt';
import duplicateThread from './controllers/duplicateThread';

const router = express.Router();

router.post("/sign-up", signUp);
router.post("/log-in", login);
router.post("/logout", logout);
router.get("/get-current-user", getCurrentUser);
router.post("/get-agents", getAgents);
router.post("/get-agent-by-name", getAgentByName);
router.post("/get-agent-by-type", getAgentByType);
router.post("/add-agent", addAgent);
router.get("/get-available-agents", getAvailableAgents);
router.post("/get-available-agent-by-type", getAvailableAgentByType)
router.post("/get-thread", getThread);
router.post("/add-thread", addThread);
router.post("/add-public-thread", addPublicThread);
router.post("/duplicate-thread", duplicateThread);
router.post("/delete-thread", deleteThread);
router.post("/add-query", addQuery);
router.post("/delete-query", deleteQuery);
router.post("/update-request-body", updateRequestBody);
router.post("/update-response-body", updateResponseBody);
router.post("/create-thread-title", createThreadTitle);
router.post("/update-thread-title", updateThreadTitle);
router.post("/remove-thread-title", removeThreadTitle);
router.post("/update-thread-is-bookmarked", updateThreadIsBookmarked);
router.post("/create-response", createResponse);
router.post("/infer-agent-type", inferAgentType);
router.post("/get-thread-updated-at", getThreadUpdatedAt);
router.post("/get-agents-updated-at", getAgentsUpdatedAt);

export default router;